id: PF6BD2213
initial_creation_type: ocr
source_metadata:
  volumes:
    92525ee62692491bb3914950fb604680:
      base_file: v061.txt
      image_group_id: I1PD96844
      title:  འཕགས་པ་བྱམས་པ་འཇུག་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 872
      volume_number: 61
